language: go
go:
  - "1.10.x"
matrix:
  include:
    os:
      - linux
      - osx
before_install:
  - sudo apt-get update 
  - sudo apt install libudev-dev libusb-1.0-0-dev
install:
  - make proto
  - go get github.com/skycoin/hardware-wallet-go
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10.2
script:
  - make check
  - make test
notifications:
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

